version: '3.8'
services:
  hiri-heatmap-flask-backend:
    build: ./backend
    network_mode: "host"
    ports:
      - "3000:3000" #host:container
  hiri-heatmap-vue-frontend:
    build: 
      context: . 
      dockerfile: frontend/Dockerfile
    ports:
      - "8081:80" #host:container


