version: '3.8'
services:
  hiri-heatmap-flask-backend:
    build: ./backend
    network_mode: "host"
    ports:
      - "3000:3000" #host:container
    volumes:
      - saved_sessions:/app/saved_sessions
  hiri-heatmap-vue-frontend:
    build: 
      context: . 
      dockerfile: frontend/Dockerfile
    ports:
      - "8081:80" #host:container

#allow saved sessions to be stored and kept
#Even when containers are stopped and started
volumes:
  saved_sessions:
